version: '3.7' # TODO: Change this version.

services:
  postgres: 
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=devspace
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: